#!/bin/bash
set -e

ROOT_DIR=$(git rev-parse --show-toplevel)

if [ -z "$ROOT_DIR" ]; then
    exit 1
fi

if [ -z "$CI_BUILD_REF_NAME" ]; then
    BRANCH=$(git branch | grep \* | cut -d ' ' -f2  | tr '[:upper:]' '[:lower:]')
else
    BRANCH=$CI_BUILD_REF_NAME
fi

REMOTE=$(git config --get remote.origin.url  | tr '[:upper:]' '[:lower:]')
IMAGES_DIR=docker/images
RANCHER_DIR=docker/rancher
RANCHER_LB_STACK=load-balancer
BUILD_ENV_VAR_NAME=APP_ENV
BUILD_ENV_VAR_DEBUG=dev
BUILD_ENV_VAR_NO_DEBUG=prod

CONFIG_FILE=$ROOT_DIR/.gitlab-docker
TMP_DIR=/tmp/.gitlab-docker
mkdir -p $TMP_DIR

declare -A BRANCH_TAG_MAP=( ["master"]="stable" ["develop"]="latest")
declare -A BRANCH_TAG_MAP_DEBUG=( ["master"]="stable-debug" ["develop"]="debug")


normalize_tag () {
    path=$1
    tag=$2

    if [ "$path" != "." ]; then
        echo $path-$tag
    else
        echo $tag
    fi
}

image_tag_from_branch () {
    path=$1
    branch=$2

    tag=${BRANCH_TAG_MAP[$branch]:-$branch}
    tag=${tag/\//-}

    normalize_tag $path $tag
}

image_tag_debug_from_branch () {
    path=$1
    branch=$2

    tag=${BRANCH_TAG_MAP_DEBUG[$branch]:-${branch}-debug}
    tag=${tag/\//-}

    normalize_tag $path $tag
}

#TAG=$(image_tag_from_branch $BRANCH)
#TAG_DEBUG=$(image_tag_debug_from_branch $BRANCH)

fail () {
    if [ $# -ne 0 ]; then
        echo $@
    fi
}

deprecated () {
    echo $@
}

re="\.[a-z]+[:/]([^./]*)/([^./]*)"
if [[ $REMOTE =~ $re ]]; then
    GIT_GROUP=`echo ${BASH_REMATCH[1]} | tr '[:upper:]' '[:lower:]'`
    GIT_PROJECT=`echo ${BASH_REMATCH[2]} | tr '[:upper:]' '[:lower:]'`
else
    fail 'Unable to extract project name from GIT remote'
fi

RANCHER_STACK=${GIT_GROUP}-${GIT_PROJECT}

DOCKER_IMAGES=.
for dir in $ROOT_DIR/$IMAGES_DIR/*; do
    if [ -d $dir ] && [ -f $dir/Dockerfile ]; then
    DOCKER_IMAGES="$DOCKER_IMAGES ${dir/$ROOT_DIR\/$IMAGES_DIR\//}"
    fi
done


if [ -f $CONFIG_FILE ]; then
    . $CONFIG_FILE
fi

# Runtime options
VERBOSITY=normal
COMMAND=$1
shift

on_exit() {
    cleanup_compiled_dockerfiles
    remove_temp_dir
}

trap "on_exit" EXIT

cleanup_compiled_dockerfiles () {
    for img in $DOCKER_IMAGES; do
        img_path=$(image_path $img)
        if [ -f $img_path/.Dockerfile ]; then
            rm $img_path/.Dockerfile # remove temporary build file
        fi
    done
}

remove_temp_dir() {
    if [ ! -z $TMP_DIR ] && [ -d $TMP_DIR ]; then
        rm -rf $TMP_DIR
    fi
}

init_config () {
    if [ ! -z "$DOCKER_REGISTRY" ]; then
        fail "Project has been already initialized"
    fi

    echo -n "Please enter docker registry domain name [$DOCKER_REGISTRY]: "
    read registry

    if [ ! -z $registry ]; then
        DOCKER_REGISTRY=$registry
    fi

    printf "DOCKER_REGISTRY=$DOCKER_REGISTRY\n" > $CONFIG_FILE
}

image_name () {
    image=$1
    branch=$2
    echo "$IMAGE_NAME:$(image_tag_fallback $image $branch)"
}


image_tag_fallback () {
    path=$1
    tag=$2

    exists=$(docker image ls --filter "reference=$IMAGE_NAME:$tag" --format "{{.Repository}}")
    if [ -z "$exists" ]; then
        if [ "$path" != "." ]; then
            echo $path
        else
            echo "latest"
        fi
    else
        echo $tag
    fi
}

image_path () {
    path=$1
    shift

    if [ "$path" != "." ]; then
        path=$IMAGES_DIR/$path
    else
        path=.
    fi
    echo "$path"
}

build () {
    image=$1
    tag=$2

    BUILD_IMAGE_DIR=$(image_path $image)
    BUILD_IMAGE_NAME="$IMAGE_NAME:$tag"
    BUILD_CONTEXT=$BUILD_IMAGE_DIR
    BUILD_DOCKERFILE=$BUILD_IMAGE_DIR/Dockerfile
    shift
    shift

    echo "Building image $BUILD_IMAGE_NAME in $BUILD_CONTEXT with $BUILD_DOCKERFILE ..."
    (
        cat $BUILD_DOCKERFILE | awk "{ if (\$1 == \"INCLUDE\") system(\"cat \"\$2); else print \$0 }" | envsubst '$BUILD_TAG' > $BUILD_CONTEXT/.Dockerfile
        exec_quietly docker build --pull $@ -t $BUILD_IMAGE_NAME -f $BUILD_CONTEXT/.Dockerfile $BUILD_CONTEXT
        rm $BUILD_CONTEXT/.Dockerfile
    )
}

push () {
    image_tag=$(image_name $1 $2)
    echo "Pushing image $image_tag ..."
    exec_quietly docker push $image_tag > /dev/null
}

exec_quietly () {
    if [ "$VERBOSITY" == "verbose" ]; then
        echo $@
        $@

        if [ $? -ne 0 ]; then
            fail "Error running: $@"
        fi
    else
        $@ > /tmp/$RANCHER_STACK.log
        if [ $? -ne 0 ]; then
            tail /tmp/$RANCHER_STACK.log
            fail "Error running: $@"
        fi
    fi
}

cmd_help () {
    EXECUTABLE=$(basename $0)

    echo $1
    echo
    echo "Usage:"
    echo "   $EXECUTABLE $2"
    echo

    exit 0
}

run_application () {
    COMMAND=$1
    shift

    if [ -z "$DOCKER_REGISTRY" ] && [ "$1" != "init" ]; then
        fail "Unknown docker registry, please setup DOCKER_REGISTRY variable in configuration file at $CONFIG_FILE"
    fi

    if [ -z "$IMAGE_NAME" ]; then
        IMAGE_NAME=$DOCKER_REGISTRY/$GIT_GROUP/$GIT_PROJECT
    fi

    case "$COMMAND" in
        config )
            echo "Docker registry [DOCKER_REGISTRY]: $DOCKER_REGISTRY"
            echo "GIT Group [GIT_GROUP]: $GIT_GROUP"
            echo "GIT Project [GIT_PROJECT]: $GIT_PROJECT"
            echo "Deploy stack [RANCHER_STACK]: $RANCHER_STACK"
            echo "Branch [BRANCH]: $BRANCH"
            echo "Docker image name [IMAGE_NAME]: $IMAGE_NAME"
            echo "Docker images: $DOCKER_IMAGES"
            echo "Image tag: $TAG"
            echo "Image Debug Tag: $TAG_DEBUG"
            echo "Temporary directory: $TMP_DIR"
            echo "Build env var: $BUILD_ENV_VAR_NAME ($BUILD_ENV_VAR_DEBUG / $BUILD_ENV_VAR_NO_DEBUG)"
            echo
            echo "You can override any of those variables in configuration file $CONFIG_FILE"

            ;;

        init )
            init_config
            init_structure
            ;;
        build )
            dev=1
            prod=1

            while [[ $# -gt 0 ]]
            do
                case "$1" in
                    -v|--verbose)
                        VERBOSITY=verbose
                    ;;
                    --no-debug)
                        dev=0
                    ;;
                    --debug)
                        prod=0
                    ;;
                    -h|--help)
                        cmd_help "Build images given as argument" "build [image1 image2 ...] [-v|--verbose]"
                        ;;
                    *)
                        IMAGES="$IMAGES $1"
                    ;;
                esac
                shift # past argument or value
            done

            if [ -z "$IMAGES" ]; then
                IMAGES=$DOCKER_IMAGES
            fi

            for image in $IMAGES; do
                if [ $prod -eq 1 ]; then
                    build $image $(image_tag_from_branch $image $BRANCH) --build-arg $BUILD_ENV_VAR_NAME=prod || fail
                fi
                if [ $dev -eq 1 ]; then
                    build $image $(image_tag_debug_from_branch $image $BRANCH) --build-arg $BUILD_ENV_VAR_NAME=dev || fail
                fi
            done

            ;;

        images )
            docker image ls --filter "reference=$IMAGE_NAME"
            ;;

        push )

            dev=1
            prod=1

            while [[ $# -gt 0 ]]
            do
                case "$1" in
                    -v|--verbose)
                        VERBOSITY=verbose
                    ;;
                    --no-debug)
                        dev=0
                    ;;
                    --debug)
                        prod=0
                    ;;
                    -h|--help)
                        cmd_help "Build images given as argument" "build [image1 image2 ...] [-v|--verbose]"
                        ;;
                    *)
                        IMAGES="$IMAGES $1"
                    ;;
                esac
                shift # past argument or value
            done

            if [ -z "$IMAGES" ]; then
                IMAGES=$DOCKER_IMAGES
            fi


            for image in $IMAGES; do
                if [ $prod -eq 1 ]; then
                    push $image $(image_tag_from_branch $image $BRANCH) || fail
                fi
                if [ $dev -eq 1 ]; then
                    push $image $(image_tag_debug_from_branch $image $BRANCH) || fail
                fi
            done
        ;;

        rancher )

            RANCHER_COMMAND=$1
            shift
            ARGS=
            if [ -d "$ROOT_DIR/$RANCHER_DIR/local" ]; then
                APP_ENV=local
            elif [ -d "$ROOT_DIR/$RANCHER_DIR/dev" ]; then
                deprecated "Use of dev environment is deprecated, change your directory name to 'local' in '$ROOT_DIR/$RANCHER_DIR'."
                APP_ENV=dev
            fi

            RANCHER_ENV_ARG="--env Default"
            if [ ! -z "$RANCHER_ENVIRONMENT" ]; then
                RANCHER_ENV_ARG="--env $RANCHER_ENVIRONMENT"
            fi

            while [[ $# -gt 0 ]]
            do
                case "$1" in
                    -v)
                        VERBOSITY=verbose
                    ;;
                    -e)
                        shift
                        APP_ENV=$1
                    ;;
                    -s)
                        shift
                        RANCHER_STACK=$1
                    ;;
                    -h|--help)
                        cmd_help "Execute rancher command" "rancher [up|down|exec|export] [-v|--verbose]"
                    ;;
                    *)
                        if [ -z $ARGS ]; then
                            ARGS=$1
                        else
                            ARGS="$ARGS $1"
                        fi
                    ;;
                esac
                shift # past argument or value
            done

            CONTEXT_DIR=$ROOT_DIR/$RANCHER_DIR/$APP_ENV
            if [ ! -d $CONTEXT_DIR ]; then
                CONTEXT_DIR=$(dirname $CONTEXT_DIR)
            fi

            cd $CONTEXT_DIR

            case "$RANCHER_COMMAND" in
                up )
                    (
                    export ROOT_DIR

#                    for IMAGE in $DOCKER_IMAGES; do
#                        declare "$IMAGE_TAG"=$(image_tag_fallback . $(image_tag_from_branch $path $BRANCH))
#                        declare "$IMAGE_TAG_DEBUG"=$(image_tag_fallback . $(image_tag_debug_from_branch $path $BRANCH))
#                    done
                    export TAG=$(image_tag_from_branch . $BRANCH)
                    export TAG_DEBUG=$(image_tag_debug_from_branch . $BRANCH)

                    export UID
                    exec_quietly rancher $RANCHER_ENV_ARG up -d -s $RANCHER_STACK --confirm-upgrade --force-upgrade $ARGS
                    )
                    ;;
                down )
                    rancher $RANCHER_ENV_ARG rm $RANCHER_STACK
                    ;;
                exec )
                    echo "rancher exec $RANCHER_STACK/$ARGS"
                    rancher $RANCHER_ENV_ARG exec -it $RANCHER_STACK/$ARGS
                ;;
                export )
                    exec_quietly rancher $RANCHER_ENV_ARG export $RANCHER_STACK
                    mv $RANCHER_STACK export
                    ;;
                * )
                    echo "Available actions: up, down"
                    ;;
            esac
        ;;

        compose )
            COMPOSE_COMMAND=$1
            shift
            ARGS=
            APP_ENV=dev

            while [[ $# -gt 0 ]]
            do
                case "$1" in
                    -v)
                        VERBOSITY=verbose
                    ;;
                    -e)
                        shift
                        APP_ENV=$1
                    ;;
                    -s)
                        shift
                        RANCHER_STACK=$1
                    ;;
                    -h|--help)
                        cmd_help "Execute rancher command" "rancher [up|down|exec|export] [-v|--verbose]"
                    ;;
                    *)
                        if [ -z $ARGS ]; then
                            ARGS=$1
                        else
                            ARGS="$ARGS $1"
                        fi
                    ;;
                esac
                shift # past argument or value
            done


            CONTEXT_DIR=$ROOT_DIR/docker/compose/$APP_ENV
            if [ ! -d $CONTEXT_DIR ]; then
                CONTEXT_DIR=$(dirname $CONTEXT_DIR)
            fi

            cd $CONTEXT_DIR

            case "$COMPOSE_COMMAND" in
                up )
                    (
                    export ROOT_DIR
                    export TAG
                    export TAG_DEBUG
                    export UID
                    exec_quietly docker-compose -p $RANCHER_STACK up -d
                    )
                    ;;
                down )
                    export ROOT_DIR
                    export TAG
                    export TAG_DEBUG
                    export UID
                    docker-compose -p $RANCHER_STACK down
                    ;;
                exec )
                    echo "rancher exec $RANCHER_STACK/$ARGS"
                    rancher exec -it $RANCHER_STACK/$ARGS
                ;;
                * )
                    echo "Available actions: up, down, exec"
                    ;;
            esac
        ;;

        cleanup )
            # WIP
            echo "Removing build images..."
            docker images | grep $IMAGE_NAME | awk '{ print $3 }' | xargs docker rmi
        ;;

        mongodump )
            # WIP
            rancher exec -i $RANCHER_STACK/mongo mongodump --gzip --archive > $ROOT_DIR/$IMAGES_DIR/mongo/backup.bz2
        ;;

        mongorestore )
            # WIP
            echo 'foo' | rancher exec -i $RANCHER_STACK/mongo xargs echo #$ROOT_DIR/$IMAGES_DIR/mongo/backup.bz2  #mongorestore --gzip --archive
        ;;

        tag )
            build=0
            debug=0
            branch=
            path=
            while [[ $# -gt 0 ]]
            do
                case "$1" in
                    --build|-b)
                        build=1
                    ;;
                    --debug)
                        debug=1
                    ;;
                    -h|--help)
                        cmd_help "Prints out an image tag" "tag [name] [-b|--build]"
                    ;;
                    *)
                        if [ -z "$path" ]; then
                            path=$1
                        elif [ -z "$tag" ]; then
                            branch=$1
                        else
                            fail "Unknown argument: $1"
                        fi
                    ;;
                esac
                shift # past argument or value
            done

            if [ -z "$path" ]; then
                path="."
            fi

            if [ -z "$branch" ]; then
                branch=$BRANCH
            fi

            if [ $build -eq 1 ]; then
                tag=$(image_tag_from_branch $path $branch)
            else
                tag=$(image_tag_fallback $path $(image_tag_from_branch $path $branch))
            fi
            if [ $debug -eq 1 ]; then
                echo ${tag}-debug
            else
                echo $tag
            fi
        ;;
        * )
            echo "GitLab Docker v0.2.0-dev"
            echo "Usage:"
            echo "   "`basename $0`" [config|build|push|deploy|cleanup]"
            echo
            echo "Examples:"
            echo "   "`basename $0`" config - show configuration"
            echo "   "`basename $0`" build <image> - build all images or image given as argument"
            echo "   "`basename $0`" push <image> - push all images or image given as argument"
            echo "   "`basename $0`" deploy - deploy project using rancher"
        ;;
    esac
}

run_application $COMMAND $@
